### ISSUE TITLE
Publisher and extension name was reversed

### ISSUE THREAD

**Issue by SnO2WMaN** [AmeerTaweel/nix-vscode-marketplace#1]
The VSCode extensions provided by Nixpkgs are, for example, `vscode-extensions.github.copilot`, (`{publisher}. {ext-name}`), but all VSCode extensions provided by this flake are like `vscode-xml.redhat`, (`{ext-name}. {publisher}`). Is there some intention behind this?

**Comment by ameertaweel** [comment]
This was totally a mistake on my part. I will fix it now.
