### ISSUE TITLE
Idea: Make NUR (Nix User Repository) support

### ISSUE THREAD

**Issue by LEv145** [AmeerTaweel/nix-vscode-marketplace#2]
https://github.com/nix-community/NUR

**Comment by ameertaweel** [comment]
Thanks for the suggestion! I made [an issue](https://github.com/nix-community/NUR/issues/480) on the NUR repo asking for their opinion.

**Comment by LEv145** [comment]
I think you can also add your flake here:

https://github.com/NixOS/nixos-search/blob/main/flakes/manual.toml
https://search.nixos.org/flakes

**Comment by ameertaweel** [comment]
This seems cool! Created a [PR](https://github.com/NixOS/nixos-search/pull/530) just now.

**Comment by ameertaweel** [comment]
It seems that `nix-vscode-marketplace` will be merged into `nixpkgs`. So I'm closing this...
