### ISSUE TITLE
Some extensions are missing

### ISSUE THREAD

**Issue by maksar** [AmeerTaweel/nix-vscode-marketplace#3]
Thanks for the effort of making it and configuring daily updates on GH Actions.

I tried to incorporate it into my MacBooks Darwin setup, but spotted some troubles.
1. Some extensions are missing, for example:
```
Name: cabal-fmt
Id: berberman.vscode-cabal-fmt
Description: Format .cabal using cabal-fmt
Version: 0.0.3
Publisher: berberman
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=berberman.vscode-cabal-fmt
```

2. Preview versions of the extensions are missing. For example: 
```
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
```

3. Something is wrong with hashing on darwin platform. For example `redhat.vscode-yaml` gives:
```
error: hash mismatch in fixed-output derivation '/nix/store/l76q3k9amxm1kgdins7x45nfa2rvcbib-vscode-yaml-1.10.20220805.zip.drv':
         specified: sha256-XFg6L+DYhq7cmbnYPkRaZJK5zPTp4yeQR24fCpUGp4I=
            got:    sha256-BZHU9FrFqsO09fllMF3+vszrGnPrfQmhVgpcNQhPv/w=
```

**Comment by ameertaweel** [comment]
Thanks for taking the time to write this!

I think that *1* and *2* are just that this flake does not have all the extensions. This is because the VSCode marketplace has about 60K extensions. This flake only has the 10K most popular ones.

Updating 10K extensions already takes a lot of time. The action takes about 6 hours to complete every time. Adding all the extensions can be done but it has to be done in a smart way. Like splitting the updates across multiple action invocations.

For *3*, what version of `redhat.vscode-yaml` are you using? Is it the VSCode Marketplace version or the OpenVSX version? We can investigate further once you tell me.

**Comment by maksar** [comment]
1. Ok, got it. There I a way to directly call `vscode-utils.extensionsFromVscodeMarketplace`, which I will use.
2. Well, I think experimental extensions should be included in the full list of 10K popular ones. For example `remote-ssh` has 12M downloads and `remote-containers` has 14.4M ass of now.
3. It is from `vscode`. I saw such behaviour earlier for Terraform extensions (one of the previous versions). If I recall correctly, the problem caused by files with different casing (`a` vs `A`) in the archive. A lot of file systems are case-insensitive (APFS is such by default). Will double-check on my own whether ie source of the issue is the same. Could you please elaborate what tool (in this repo) calculates the SHA of the achieve?

**Comment by maksar** [comment]
Turns out, the problem isn't with case-insensitivity. I will post here my investigations.
```
curl https://redhat.gallery.vsassets.io/_apis/public/gallery/publisher/redhat/extension/vscode-yaml/1.10.20220805/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage -o extension.zip

nix hash to-sri --type sha256 `nix-hash --flat --base32 --type sha256 extension.zip`
```

On Linux (x86_64): `sha256-BZHU9FrFqsO09fllMF3+vszrGnPrfQmhVgpcNQhPv/w=`
On Darwin (X86_64): `sha256-Q1R+2t/tWI3haoF5fW7k2413BLIMf1ImM4J9CUrtjnQ=`


Linux:
```
Archive:  extension.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
    2734  Defl:N      846  69% 2022-08-29 09:36 a4aa3a10  extension.vsixmanifest
     462  Defl:N      211  54% 2022-08-29 09:36 fb92e1c0  [Content_Types].xml
      32  Defl:N       33  -3% 2022-08-29 09:32 6c577083  extension/.prettierignore
   43404  Defl:N    10246  76% 2022-08-29 09:36 a11ef2bf  extension/CHANGELOG.md
    1421  Defl:N      674  53% 2022-08-29 09:32 b174baf6  extension/DCO
  274811  Defl:N    65038  76% 2022-08-29 09:35 eccaa7e3  extension/dist/extension-web.js
  532120  Defl:N   145647  73% 2022-08-29 09:36 90ac9b0b  extension/dist/extension.js
     120  Defl:N      104  13% 2022-08-29 09:36 b7e399eb  extension/dist/extension.js.LICENSE.txt
  572349  Defl:N   152362  73% 2022-08-29 09:35 016a5d09  extension/dist/languageserver-web.js
     147  Defl:N      129  12% 2022-08-29 09:35 86bc08f1  extension/dist/languageserver-web.js.LICENSE.txt
  852778  Defl:N   230647  73% 2022-08-29 09:36 d68ac288  extension/dist/languageserver.js
     929  Defl:N      491  47% 2022-08-29 09:36 9bfffad9  extension/dist/languageserver.js.LICENSE.txt
    9569  Defl:N     9507   1% 2022-08-29 09:32 4eef41ce  extension/icon/icon128.png
     733  Defl:N      310  58% 2022-08-29 09:32 d6d3471f  extension/language-configuration.json
    1081  Defl:N      635  41% 2022-08-29 09:32 4eb3ccf1  extension/LICENSE.txt
    8193  Defl:N     2757  66% 2022-08-29 09:34 fce8ef94  extension/package.json
   11487  Defl:N     4100  64% 2022-08-29 09:36 bb1f2f95  extension/README.md
   21681  Defl:N     3074  86% 2022-08-29 09:32 ca7fcbc5  extension/syntaxes/yaml.tmLanguage.json
    3082  Defl:N     1014  67% 2022-08-29 09:32 8b00e23a  extension/thirdpartynotices.txt
     709  Defl:N      328  54% 2022-08-29 09:32 86befb6c  extension/USAGE_DATA.md
 1658615  Defl:N   383745  77% 2022-08-29 09:23 3a49c5ea  extension/node_modules/prettier/index.js
  144355  Defl:N    41759  71% 2022-08-29 09:23 70bb91cb  extension/node_modules/prettier/parser-yaml.js
  289480  Defl:N    68879  76% 2022-08-29 09:23 72dfd1a1  extension/node_modules/prettier/third-party.js
--------          -------  ---                            -------
 4430292          1122536  75%                            23 files
```

Darwin:
```
Archive:  extension.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
    2839  Defl:N      883  69% 08-05-2022 08:31 18a7abd2  extension.vsixmanifest
     462  Defl:N      211  54% 08-05-2022 08:31 fb92e1c0  [Content_Types].xml
      32  Defl:N       33  -3% 08-05-2022 08:24 6c577083  extension/.prettierignore
   42634  Defl:N    10121  76% 08-05-2022 08:31 727f83cb  extension/CHANGELOG.md
    1421  Defl:N      674  53% 08-05-2022 08:24 b174baf6  extension/DCO
  276663  Defl:N    65451  76% 08-05-2022 08:26 916ae5da  extension/dist/extension-web.js
  533519  Defl:N   145951  73% 08-05-2022 08:27 029b9569  extension/dist/extension.js
     270  Defl:N      201  26% 08-05-2022 08:27 1daaac8b  extension/dist/extension.js.LICENSE.txt
  594964  Defl:N   157940  74% 08-05-2022 08:27 6a0563e8  extension/dist/languageserver-web.js
     147  Defl:N      129  12% 08-05-2022 08:27 86bc08f1  extension/dist/languageserver-web.js.LICENSE.txt
  880274  Defl:N   233701  74% 08-05-2022 08:27 8a034a24  extension/dist/languageserver.js
     929  Defl:N      491  47% 08-05-2022 08:27 9bfffad9  extension/dist/languageserver.js.LICENSE.txt
    9569  Defl:N     9507   1% 08-05-2022 08:24 4eef41ce  extension/icon/icon128.png
     733  Defl:N      310  58% 08-05-2022 08:24 d6d3471f  extension/language-configuration.json
    1081  Defl:N      635  41% 08-05-2022 08:24 4eb3ccf1  extension/LICENSE.txt
    8200  Defl:N     2764  66% 08-05-2022 08:25 1994531f  extension/package.json
   11487  Defl:N     4100  64% 08-05-2022 08:31 bb1f2f95  extension/README.md
   21681  Defl:N     3074  86% 08-05-2022 08:24 ca7fcbc5  extension/syntaxes/yaml.tmLanguage.json
    3082  Defl:N     1014  67% 08-05-2022 08:24 8b00e23a  extension/thirdpartynotices.txt
     709  Defl:N      328  54% 08-05-2022 08:24 86befb6c  extension/USAGE_DATA.md
 1658615  Defl:N   383745  77% 08-05-2022 08:24 3a49c5ea  extension/node_modules/prettier/index.js
  144355  Defl:N    41759  71% 08-05-2022 08:24 70bb91cb  extension/node_modules/prettier/parser-yaml.js
  289480  Defl:N    68879  76% 08-05-2022 08:24 72dfd1a1  extension/node_modules/prettier/third-party.js
--------          -------  ---                            -------
 4483146          1131901  75%                            23 files
```

So archives ARE different: `Version="1.10.20220805"` vs `Version="1.10.1"`. So I can conclude that marketplace just returns WRONG archive. Requested version (in the URL) was `1.10.20220805`, but it decided to give `1.10.1` for some reason... I don't have explanation for this.

**Comment by maksar** [comment]
Maybe there is some url query parameter to be... I don't know... correct? ;)

**Comment by maksar** [comment]
Interestingly, the hash which was captured by `nvfetch` machinery is different from both. Can you please check which version does actual dowloaded archive end up having in your nix store (if that is even possible as it happens on GitHub actions)?

**Comment by ameertaweel** [comment]
Very interesting findings.

The output of `nvfetch` that ran on the GitHub machine is:
`sha256-BZHU9FrFqsO09fllMF3+vszrGnPrfQmhVgpcNQhPv/w=`
You can find this in `generated/vscode-marketplace/generated.nix`, line 96249.

However, the more interesting thing is that when I run these commands on my Linux machine:
```bash
curl https://redhat.gallery.vsassets.io/_apis/public/gallery/publisher/redhat/extension/vscode yaml/1.10.20220805/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage -o extension.zip

nix hash to-sri --type sha256 $(nix-hash --flat --base32 --type sha256 extension.zip)
```
I get this output:
`sha256-Q1R+2t/tWI3haoF5fW7k2413BLIMf1ImM4J9CUrtjnQ=`
Which is the same as what you got on Darwin, not on Linux.

**Comment by ameertaweel** [comment]
I think we can conclude that the wrong results returned by the VSCode Marketplace are not related to the OS. But something else...

**Comment by ameertaweel** [comment]
I also think that wrong results are not random. I re-downloaded the file and re-calculated the hash 10 times on my machine, and got the same result every time. So there is something that causes the API to return wrong results.

**Comment by ameertaweel** [comment]
No it's actually random. I ran the same commands over and over, and then I got the `sha256-BZHU9FrFqsO09fllMF3+vszrGnPrfQmhVgpcNQhPv/w=`. But I also got another result that you did not get: `sha256-M9o5yL/GAh3w2zLTNW7VlxIbP610A2V/Hi5oB+Xaw+U=`.

**Comment by ameertaweel** [comment]
It's a big issue if the API is not deterministic. The only solution I can think of is hosting the extensions and providing a non-official but a deterministic API. But I'm not sure how to do that either. I can't host the extensions in this repo for two reasons:

1. I don't think GitHub will allow such huge repository.
2. Even if GitHub allows me to store all the extensions, developing the repo will be a nightmare, because I will have to clone everything locally.

**Comment by ameertaweel** [comment]
Also, I checked why I don't have these extensions:

+ `ms-vscode-remote.remote-containers`
+ `ms-vscode-remote.remote-ssh`
+ `ms-vscode-remote.remote-ssh-edit`

And it was because they all have these flags: `validated, public, preview`, while my code only gets extensions with flags `validated, public`. I fixed that with the latest commit. So your point 2 should be solved by the next automatic update.

Now only 1 and 3 remain.

**Comment by maksar** [comment]
One (naive and not practical) way to work-around would be to actually unpack the `extension.vsixmanifest` file from the downloaded archive and get the `Version` out of XML. If doesn't match – repeat the download.

Oh, can you actually check the contents of that file for the result with unusual hash?

What touches reason of such behaviour – `gallery.vsassets.io` might be a CDN proxy, which isn't invalidated properly.
It is possible to try using such URLs, but those are rate-limited heavily...
`https://marketplace.visualstudio.com/_apis/public/gallery/publishers/redhat/vsextensions/vscode-yaml/1.10.20220805/vspackage`

**Comment by ameertaweel** [comment]
I'm afraid I lost that file. I wrote a script to keep running the commands and just show the different outputs it got, so whenever it ran `curl` it overrides the file. And the unusual result was not the last result.

I don't think using the rate-limited URLs would work for this flake because of the huge number of extensions it has.

But I got an interesting question in mind. Even if we re-download the file until we get the correct version, or we use the rate-limited URLs, there is no guarantee that Nix will receive the correct file in the first place. The API might serve it a wrong version and it will not matter if the hash on this flake is correct or not. What do you think about this?

**Comment by maksar** [comment]
You are correct. To overcome, that would only push the problem to the user's hands. Lets pause for a while and maybe raise a question in vscode forums. The only correct way to fix that is to make a download endpoint to be stable.

**Comment by maksar** [comment]
Heh, there is one more problem with preview extensions. Some of them might not be compatible with vscode version (even from unstable channel). 

ms-vscode-remote.remote-containers `v0.250.0`:
```
Extension is not compatible with Code 1.70.2. Extension requires: ^1.71.0.
```

Strangely enough, either `v0.252.0` or `v0.251.0` work fine.

**Comment by ameertaweel** [comment]
Where do you think is a good place to ask about this? They have a repository for the official VSCode Marketplace API, but they are not responsive over there...

**Comment by ameertaweel** [comment]
About the VSCode version requirements, maybe we can extract that from `package.json` of extensions. But then we need to add it in some way to the flake.
