### ISSUE TITLE
Moving to nix-community

### ISSUE THREAD

**Issue by deemp** [AmeerTaweel/nix-vscode-marketplace#7]
Hi @AmeerTaweel! I moved my fork to `nix-community`. It's now [here](https://github.com/nix-community/nix-vscode-extensions). This is to have it in a safe place before we include extensions into `nixpkgs`. Would you like to become a maintainer?

**Comment by ameertaweel** [comment]
Yeah sure. Should I archive this repo?

**Comment by deemp** [comment]
As you wish. I guess anyway there's no need to run GH action here

**Comment by ameertaweel** [comment]
Okay, I will archive this repo.
